import type { TableNodeType, FkEdgeType, ColumnDef } from "@/lib/schema";

// Quote a PostgreSQL identifier safely.
// PostgreSQL allows any character in a quoted identifier as long as embedded
// double-quotes are doubled. Without this escaping, a malicious table name
// like `users"; DROP TABLE x; --` would inject SQL. This is the SECURITY
// boundary for the export — every user-provided name goes through here.
function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

function renderColumnType(col: ColumnDef): string {
  if (col.type === "VARCHAR" && col.length) {
    return `VARCHAR(${col.length})`;
  }
  return col.type;
}

function renderColumn(col: ColumnDef): string {
  const parts: string[] = [
    quoteIdent(col.name || "unnamed"),
    renderColumnType(col),
  ];
  // PRIMARY KEY in PostgreSQL implies NOT NULL + UNIQUE, so we suppress the
  // redundant clauses to keep the generated SQL clean.
  if (col.primaryKey) {
    parts.push("PRIMARY KEY");
  } else {
    if (col.notNull) parts.push("NOT NULL");
    if (col.unique) parts.push("UNIQUE");
  }
  return `  ${parts.join(" ")}`;
}

function renderTable(node: TableNodeType): string {
  const tableName = quoteIdent(node.data.name || "unnamed");
  const columns = node.data.columns;

  if (columns.length === 0) {
    // PostgreSQL doesn't accept zero-column tables. Emit a comment so the user
    // sees something meaningful instead of broken SQL.
    return `-- Table "${node.data.name}" has no columns; skipping.\n`;
  }

  const body = columns.map(renderColumn).join(",\n");
  return `CREATE TABLE ${tableName} (\n${body}\n);`;
}

// Resolve an edge's source/target column ids back to the names needed for
// the FK statement. Returns null if any lookup fails (e.g. node was deleted
// without removing the edge — shouldn't normally happen but be defensive).
function resolveEdge(
  edge: FkEdgeType,
  nodes: TableNodeType[],
): {
  sourceTable: string;
  sourceColumn: string;
  targetTable: string;
  targetColumn: string;
} | null {
  const sourceNode = nodes.find((n) => n.id === edge.source);
  const targetNode = nodes.find((n) => n.id === edge.target);
  if (!sourceNode || !targetNode || !edge.data) return null;

  const sourceCol = sourceNode.data.columns.find(
    (c) => c.id === edge.data!.sourceColumnId,
  );
  const targetCol = targetNode.data.columns.find(
    (c) => c.id === edge.data!.targetColumnId,
  );
  if (!sourceCol || !targetCol) return null;

  return {
    sourceTable: sourceNode.data.name || "unnamed",
    sourceColumn: sourceCol.name || "unnamed",
    targetTable: targetNode.data.name || "unnamed",
    targetColumn: targetCol.name || "unnamed",
  };
}

function renderForeignKey(
  edge: FkEdgeType,
  nodes: TableNodeType[],
): string | null {
  const resolved = resolveEdge(edge, nodes);
  if (!resolved) return null;

  // The FK lives on the SOURCE side: source table has the column that points
  // to the target. (Connections are dragged from a column → another column
  // it should reference.)
  return `ALTER TABLE ${quoteIdent(resolved.sourceTable)} ADD CONSTRAINT ${quoteIdent(
    `fk_${resolved.sourceTable}_${resolved.sourceColumn}`,
  )} FOREIGN KEY (${quoteIdent(resolved.sourceColumn)}) REFERENCES ${quoteIdent(
    resolved.targetTable,
  )} (${quoteIdent(resolved.targetColumn)});`;
}

export function generateSql(
  nodes: TableNodeType[],
  edges: FkEdgeType[],
  schemaName: string = "my_schema",
): string {
  const trimmedSchema = schemaName.trim();
  const header = `-- Generated by Draft_SQL\n`;

  // Emit CREATE SCHEMA + SET search_path only when a schema name is provided.
  // search_path is session-local, so pasting this into psql affects only that
  // session — safe and reversible. With no schema name, tables go into the
  // current search_path (typically "public").
  const schemaBlock = trimmedSchema
    ? `CREATE SCHEMA IF NOT EXISTS ${quoteIdent(trimmedSchema)};\nSET search_path TO ${quoteIdent(trimmedSchema)};\n\n`
    : "";

  if (nodes.length === 0) {
    return `${header}${schemaBlock}-- No tables defined.\n`;
  }

  const tables = nodes.map(renderTable).join("\n\n");
  const fks = edges
    .map((e) => renderForeignKey(e, nodes))
    .filter((s): s is string => s !== null);

  const fkBlock = fks.length > 0 ? `\n\n${fks.join("\n")}` : "";

  return `${header}\n${schemaBlock}${tables}${fkBlock}\n`;
}

// Trigger a browser download for arbitrary text content.
export function downloadSql(content: string, filename: string = "schema.sql") {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
